version: '2'

services:
    front:
      build:
        context: ./docker/nginx
        args:
            - VIRTUAL_HOST=${VIRTUAL_HOST}
      container_name: ${APP_NAME}-front
      expose:
        - 80
      ports:
        - "80:80"
      links:
        - php
      volumes_from:
        - php
      volumes:
        - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
        - ${SRC}:/var/www/html
        - ./docker/logs/nginx:/var/log/nginx
    php:
      container_name: ${APP_NAME}-php
      build:
        context: ./docker/php
        args:
            - INSTALL_XDEBUG=${PHP_FPM_INSTALL_XDEBUG}
            - GITHUB_API_TOKEN=${GITHUB_API_TOKEN}
      environment:
            PHP_IDE_CONFIG: serverName=${VIRTUAL_HOST}
      expose:
          - 9000
      links:
          - mysql
      volumes:
          - ${SRC}:/var/www/html
    mysql:
      container_name: ${APP_NAME}-mysql
      image: mysql:5.7
      environment:
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - MYSQL_ROOT_HOST=%
      expose:
          - 3306
      volumes:
        - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
#        - ./docker/mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
#        - ./docker/mysql/database:/var/lib/mysql

    memcached:
      container_name: ${APP_NAME}-memcached
      image: memcached:alpine
      expose:
          - 11211
    adminer:
        container_name: ${APP_NAME}-adminer
        image: adminer:latest
        ports:
            - 8080:8080
        links:
            - mysql
        depends_on:
            - mysql
